### PR TITLE
Example: Simulated hardware resources

### PR DESCRIPTION
**Pull request by torsteingrindvik**
Hi, thanks for `tokio-tower`!

I needed to get a feel for it and do a sort of MVP for my use case, so I wrote an example.

The example architecture (diagram source and png also checked in to example folder, used [excalidraw](https://github.com/excalidraw/excalidraw)):

hardware-resources

The example touches on:

- `tokio-tower`
  - `pipeline::Client`
  - `pipeline::Server`
- `tower`:
  - `Buffer`
  - `Balance` (with `ServiceList`)
  - `Service` naturally (and `BoxService`)
  - `Steer`
  - `Filter`

The theme is an imagined situation where some hardware units are exposed as services on a server.

### CODE REVIEW

**Comment by torsteingrindvik** [comment]
Checks failed due to an unrelated clippy lint in `src/mediator.rs`, so followed clippy's suggestion there.

**Comment by jonhoo** [comment]
Hi there! Thanks for the suggestion. I think having an example like this would be valuable, though unless I'm missing something this could be significantly simplified by using [`tower::buffer`](https://docs.rs/tower/0.4/tower/buffer/index.html)? It will take care of the multiplexing for you, and basically lets you have multiple handles that all send requests over a single backing `Service`. And then for the middleware you can wrap different middleware to your heart's content around the `Buffer` handle, since it implements both `Clone` (so you can have multiple handles with different middleware) and `Service` (so you can wrap it with middleware).

**Comment by torsteingrindvik** [comment]
Thanks a lot for those pointers! I understand a bit more now.

I kinda changed the whole scenario after I started using `Buffer`.
I updated the description.

The new scenario shoehorns the use of `Balance`, but I think it's an interesting thing to have an example of.

There are a few things I'm not 100% happy with:

- I use a `Pin<Box<dyn Future<..>>` type for the services. Not sure if this is the best approach.
- The `HardwareManager` is essentially a hash map from some arbitrary id (`usize`) to a service. It sounds like perhaps `Steer` could be used here instead.

I appreciate any other pointers you may have.

**Comment by jonhoo** [comment]
Hmm, this feels more like an example of tower now than it does of `tokio-tower`. Things like Steer, Balance, and Filter are all tower constructs that `tokio-tower` doesn't know anything about, and aren't required when using it. Maybe open a PR with the example there, possibly without the `tokio_tower` bit?

**Comment by torsteingrindvik** [comment]
Yes, I agree the example turned out more `tower` heavy than `tokio-tower` specifically.
I'll consider opening a PR there.

**Pull request closed without merging**
